import React from 'react'
import Navbar from './Navbar'
import Footer from './Footer'
import Head from 'next/head'

function Layout({children}) {
  return (
    <div className=' max-w-1280 m-auto'>
        <Head>
        <title>Wildermere Estates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <header>
            <Navbar />
        </header>
        <main>
            {children}
        </main>
        <footer>
            <Footer/>
        </footer>

    </div>
  )
}

export default Layout